# Generated by Django 5.2.6 on 2025-09-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(help_text='De-identified subject ID (e.g., SUBJ-ABC12345)', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrudeSample',
            fields=[
                ('barcode', models.CharField(help_text='Unique identifier for the sample (e.g., SUBJ-ABC123_2024-10-05_stool)', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('collection_date', models.DateField(help_text='Date when the sample was collected')),
                ('sample_source', models.CharField(choices=[('Stool', 'Stool'), ('Oral', 'Oral Swab'), ('Nasal', 'Nasal Swab'), ('Skin', 'Skin Swab'), ('Blood', 'Blood'), ('Tissue', 'Tissue'), ('Other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this sample', null=True)),
                ('status', models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AVAILABLE', help_text='The current status of the sample', max_length=20)),
                ('sequence_filename', models.CharField(blank=True, help_text='Filename of the associated sequence data', max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, help_text='Name of the project or cohort', max_length=255, null=True)),
                ('source_file', models.CharField(blank=True, help_text='Source file and sheet where this data originated from', max_length=255, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.subject')),
            ],
            options={
                'verbose_name': 'Crude Sample',
                'verbose_name_plural': 'Crude Samples',
                'ordering': ['subject', 'collection_date'],
            },
        ),
    ]
